name: Deploy to ECS

on:
  push:
    branches:
      - sky

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Build and push Docker image
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 240243041622.dkr.ecr.eu-west-2.amazonaws.com
          docker build -t veracode-github-app-repo .
          docker tag veracode-github-app-repo:latest 240243041622.dkr.ecr.eu-west-2.amazonaws.com/veracode-github-app-repo:latest
          docker push 240243041622.dkr.ecr.eu-west-2.amazonaws.com/veracode-github-app-repo:latest
